import './globals.css'
import type { Metadata } from 'next'
import { fonts } from '@/lib/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html className={fonts} lang="en" suppressHydrationWarning>
    <body className="flex min-h-full flex-col">{children}</body>
  </html>
)

export default RootLayout
